package application.controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.Iterator;
import java.util.List;
import java.util.ResourceBundle;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.query.Query;

import application.Main;
import hibernate.UtilesHibernate;
import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;
import pojos.Actividad;
import pojos.Grupo;
import pojos.GrupoActividad;
import pojos.Profesor;
import pojos.TramoHorario;
import pojos.Usuario;

public class MainViewController implements Initializable{
	@FXML
	private Label LH1;
	@FXML
	private Label LH2;
	@FXML
	private Label LH3;
	@FXML
	private Label LH4;
	@FXML
	private Label LH5;
	@FXML
	private Label LH6;
	@FXML
	private Label LH7;
	@FXML
	private Label LH9;
	@FXML
	private Label LH8;
	@FXML
	private TextArea TA1;
	@FXML
	private TextArea TA2;
	@FXML
	private TextArea TA3;
	@FXML
	private TextArea TA4;
	@FXML
	private TextArea TA5;
	@FXML
	private TextArea TA6;
	@FXML
	private TextArea TA7;
	@FXML
	private TextArea TA8;
	@FXML
	private TextArea TA9;
	@FXML
	private TextArea TA10;
	@FXML
	private TextArea TA11;
	@FXML
	private TextArea TA16;
	@FXML
	private TextArea TA21;
	@FXML
	private TextArea TA26;
	@FXML
	private TextArea TA31;
	@FXML
	private TextArea TA36;
	@FXML
	private TextArea TA41;
	@FXML
	private TextArea TA12;
	@FXML
	private TextArea TA13;
	@FXML
	private TextArea TA14;
	@FXML
	private TextArea TA15;
	@FXML
	private TextArea TA17;
	@FXML
	private TextArea TA22;
	@FXML
	private TextArea TA27;
	@FXML
	private TextArea TA32;
	@FXML
	private TextArea TA37;
	@FXML
	private TextArea TA42;
	@FXML
	private TextArea TA18;
	@FXML
	private TextArea TA19;
	@FXML
	private TextArea TA20;
	@FXML
	private TextArea TA23;
	@FXML
	private TextArea TA28;
	@FXML
	private TextArea TA33;
	@FXML
	private TextArea TA38;
	@FXML
	private TextArea TA43;
	@FXML
	private TextArea TA24;
	@FXML
	private TextArea TA25;
	@FXML
	private TextArea TA29;
	@FXML
	private TextArea TA34;
	@FXML
	private TextArea TA39;
	@FXML
	private TextArea TA44;
	@FXML
	private TextArea TA30;
	@FXML
	private TextArea TA35;
	@FXML
	private TextArea TA40;
	@FXML
	private TextArea TA45;
	
	private TextArea[][] semana;
	
	private Label[] horas;
	
	private Main gestorVentanas;
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		Label[] horasI = {LH1, LH2, LH3, LH4, LH5, LH6, LH7, LH8, LH9};
		horas = horasI;
		
		TextArea[][] semanaI = {
				{TA1, TA6, TA11, TA16, TA21, TA26, TA31, TA36, TA41},
				{TA2, TA7, TA12, TA17, TA22, TA27, TA32, TA37, TA42},
				{TA3, TA8, TA13, TA18, TA23, TA28, TA33, TA38, TA43},
				{TA4, TA9, TA14, TA19, TA24, TA29, TA34, TA39, TA44},
				{TA5, TA10, TA15, TA20, TA25, TA30, TA35, TA40, TA45}};
		semana = semanaI;
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void LogOut(ActionEvent event) {
		gestorVentanas.setUsuario(null);
		gestorVentanas.muestraLogin();
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void Exit(ActionEvent event) {
		Platform.exit();
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void Guardia(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void About(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void opciones(ActionEvent event) {
		gestorVentanas.muestraOptions();
	}
	
	public void setGestorVentanas(Main gestor) {
		this.gestorVentanas = gestor;
		CargaDatos();
	}
	
	private void CargaDatos() {
		SessionFactory SF = UtilesHibernate.getSessionFactory();
		Session session = SF.getCurrentSession();
		
		session.beginTransaction();
		Query q = session.createQuery("SELECT t FROM TramoHorario t WHERE numeroDia = 1");
		List<TramoHorario> tramos = (List<TramoHorario>)q.list();
		for (int i = 0; i < horas.length; i++) {
			horas[i].setText(tramos.get(i).getHoraInicio()+"\n"+tramos.get(i).getHoraFinal());
		}

		Usuario u = this.gestorVentanas.getUsuario();
		Query pro = session.createQuery("SELECT p FROM profesor p WHERE num_usuario = :id");
		pro.setParameter("id", u.getNumUsuario());
		Profesor p = (Profesor) pro.getSingleResult();
		
		Query qe = session.createQuery("SELECT a FROM actividad a WHERE num_Profesor = :id");
		qe.setParameter("id", p.getNumProfesor());
		List<Actividad> actividades = (List<Actividad>)qe.list();
		cargaHorario(actividades);
		session.getTransaction().commit();
		session.close();
	}
	
	private void cargaHorario(List<Actividad> actividades) {
		for (Actividad actividad : actividades) {
			TramoHorario t = actividad.getTramo();
			if(t.getNumeroDia() == 1) {
				if(t.getNumeroHora() == 1) {
					semana[0][0].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[0][0].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
					
				}
				if(t.getNumeroHora() == 2) {
					semana[0][1].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[0][1].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 3) {
					semana[0][2].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[0][2].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 4) {
					semana[0][3].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[0][3].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 5) {
					semana[0][4].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[0][4].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 6) {
					semana[0][5].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[0][5].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}	
				}
				if(t.getNumeroHora() == 7) {
					semana[0][6].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[0][6].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 8) {
					semana[0][7].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[0][7].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 9) {
					semana[0][8].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[0][8].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
			}
			if(t.getNumeroDia() == 2) {
				if(t.getNumeroHora() == 1) {
					semana[1][0].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[1][0].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
					
				}
				if(t.getNumeroHora() == 2) {
					semana[1][1].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[1][1].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 3) {
					semana[1][2].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[1][2].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 4) {
					semana[1][3].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[1][3].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 5) {
					semana[1][4].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[1][4].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 6) {
					semana[1][5].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[1][5].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}	
				}
				if(t.getNumeroHora() == 7) {
					semana[1][6].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[1][6].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 8) {
					semana[1][7].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[1][7].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 9) {
					semana[1][8].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[1][8].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
			}
			if(t.getNumeroDia() == 3) {
				if(t.getNumeroHora() == 1) {
					semana[2][0].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[2][0].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
					
				}
				if(t.getNumeroHora() == 2) {
					semana[2][1].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[2][1].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 3) {
					semana[2][2].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[2][2].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 4) {
					semana[2][3].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[2][3].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 5) {
					semana[2][4].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[2][4].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 6) {
					semana[2][5].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[2][5].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}	
				}
				if(t.getNumeroHora() == 7) {
					semana[2][6].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[2][6].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 8) {
					semana[2][7].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[2][7].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 9) {
					semana[2][8].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[2][8].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
			}
			if(t.getNumeroDia() == 4) {
				if(t.getNumeroHora() == 1) {
					semana[3][0].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[3][0].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
					
				}
				if(t.getNumeroHora() == 2) {
					semana[3][1].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[3][1].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 3) {
					semana[3][2].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[3][2].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 4) {
					semana[3][3].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[3][3].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 5) {
					semana[3][4].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[3][4].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 6) {
					semana[3][5].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[3][5].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}	
				}
				if(t.getNumeroHora() == 7) {
					semana[3][6].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[3][6].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 8) {
					semana[3][7].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[3][7].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 9) {
					semana[3][8].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[3][8].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
			}
			if(t.getNumeroDia() == 5) {
				if(t.getNumeroHora() == 1) {
					semana[4][0].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[4][0].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
					
				}
				if(t.getNumeroHora() == 2) {
					semana[4][1].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[4][1].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 3) {
					semana[4][2].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[4][2].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 4) {
					semana[4][3].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[4][3].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 5) {
					semana[4][4].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[4][4].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 6) {
					semana[4][5].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[4][5].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}	
				}
				if(t.getNumeroHora() == 7) {
					semana[4][6].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[4][6].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 8) {
					semana[4][7].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[4][7].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
				if(t.getNumeroHora() == 9) {
					semana[4][8].setText(
							"Asignatira: "+actividad.getAsignatura().getNombre()+
							"\n Aula"+actividad.getAula().getNombre()
							);
					List<GrupoActividad> gruposa = actividad.getGrupos();
					for (GrupoActividad gruposAct : gruposa) {
						semana[4][8].appendText("\n Grupo: "+gruposAct.getGrupo().getNombre());
					}
				}
			}
		}
	}
}
