package application.controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

public class MainViewController implements Initializable{
	@FXML
	private Label LH1;
	@FXML
	private Label LH2;
	@FXML
	private Label LH3;
	@FXML
	private Label LH4;
	@FXML
	private Label LH5;
	@FXML
	private Label LH6;
	@FXML
	private Label LH7;
	@FXML
	private Label LH9;
	@FXML
	private Label LH8;
	@FXML
	private TextArea TA1;
	@FXML
	private TextArea TA2;
	@FXML
	private TextArea TA3;
	@FXML
	private TextArea TA4;
	@FXML
	private TextArea TA5;
	@FXML
	private TextArea TA6;
	@FXML
	private TextArea TA7;
	@FXML
	private TextArea TA8;
	@FXML
	private TextArea TA9;
	@FXML
	private TextArea TA10;
	@FXML
	private TextArea TA11;
	@FXML
	private TextArea TA16;
	@FXML
	private TextArea TA21;
	@FXML
	private TextArea TA26;
	@FXML
	private TextArea TA31;
	@FXML
	private TextArea TA36;
	@FXML
	private TextArea TA41;
	@FXML
	private TextArea TA12;
	@FXML
	private TextArea TA13;
	@FXML
	private TextArea TA14;
	@FXML
	private TextArea TA15;
	@FXML
	private TextArea TA17;
	@FXML
	private TextArea TA22;
	@FXML
	private TextArea TA27;
	@FXML
	private TextArea TA32;
	@FXML
	private TextArea TA37;
	@FXML
	private TextArea TA42;
	@FXML
	private TextArea TA18;
	@FXML
	private TextArea TA19;
	@FXML
	private TextArea TA20;
	@FXML
	private TextArea TA23;
	@FXML
	private TextArea TA28;
	@FXML
	private TextArea TA33;
	@FXML
	private TextArea TA38;
	@FXML
	private TextArea TA43;
	@FXML
	private TextArea TA24;
	@FXML
	private TextArea TA25;
	@FXML
	private TextArea TA29;
	@FXML
	private TextArea TA34;
	@FXML
	private TextArea TA39;
	@FXML
	private TextArea TA44;
	@FXML
	private TextArea TA30;
	@FXML
	private TextArea TA35;
	@FXML
	private TextArea TA40;
	@FXML
	private TextArea TA45;
	
	private TextArea[][] semana = {
			{TA1, TA6, TA11, TA16, TA21, TA26, TA31, TA36, TA41},
			{TA2, TA7, TA12, TA17, TA22, TA27, TA32, TA37, TA42},
			{TA3, TA8, TA13, TA18, TA23, TA28, TA33, TA38, TA43},
			{TA4, TA9, TA14, TA19, TA24, TA29, TA34, TA39, TA44},
			{TA5, TA10, TA15, TA20, TA25, TA30, TA35, TA40, TA45}};
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void LogOut(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void Exit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void Guardia(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void About(ActionEvent event) {
		// TODO Autogenerated
	}
}
